Repository Slynnex/front-banco, pull requests merged in 2022-04, with the labels that each got.

#10 [IMP] executive crud done
  package-lock.json
  package.json
  src/assets/Loader.js
  src/index.js
  src/pages/Executives.js
  src/styles/Loader.css
  src/styles/executives.css
Labels: review needed

#18 Denominations completed
  src/App.js
  src/context/Denominations/DenominationsContext.js
  src/context/Denominations/denominationsDataContext.js
  src/pages/Denominations/Denominations.js
  src/pages/Denominations/ModalDenominations.js
Labels: done

#24 [IMP] creditdetails and interest crud
  src/App.js
  src/context/CreditDetails/CreditDetailsContext.js
  src/context/CreditDetails/creditDetailsDataContext.js
  src/context/Interests/InterestsContext.js
  src/context/Interests/interestsDataContext.js
  src/pages/CreditDetails/CreditDetails.js
  src/pages/CreditDetails/ModalCreditDetails.js
  src/pages/Interests/Interests.js
  src/pages/Interests/ModalInterests.js
  src/pages/Login.js
  src/styles/login.css
Labels: done

#27 [IMP] change login design
  src/pages/Login.js
Labels: done

#29 Validator#20 pr
  src/pages/Denominations/Denominations.js
  src/pages/Denominations/ModalDenominations.js
Labels: done

#31 Validation of Positions and Areas completed #30
  src/pages/PositionArea/ModalArea.js
  src/pages/PositionArea/ModalPosition.js
  src/pages/PositionArea/PositionArea.js
Labels: done

#33 Validate comissions#32 pr
  src/context/Commissions/CommissionsController.js
  src/pages/Commissions/Commissions.js
  src/pages/Commissions/ModalCommissions.js
Labels: done

#38 [IMP] cuts without validations
  src/App.js
  src/context/Cuts/CutsContext.js
  src/context/Cuts/cutsDataContext.js
  src/pages/CreditDetails/CreditDetails.js
  src/pages/Cuts/Cuts.js
  src/pages/Cuts/ModalCuts.js
  src/pages/Interests/Interests.js
Labels: done

#46 [IMP] update clients
  src/components/show_info/Show_info.js
  src/pages/Clients/Clients.js
  src/pages/Clients/ModalClients.js
  src/pages/Clients/TableClient.js
Labels: assigned, done

#52 [IMP] charts
  package-lock.json
  package.json
  src/components/show_info/Show_info.js
  src/pages/Dashboard.js
Labels: review needed

#51 validation of concepts completed
  src/pages/Concepts/Concepts.js
  src/pages/Concepts/ModalConcepts.js
Labels: done

#56 Agregar cuentas
  src/pages/Accounts/Accounts.js
  src/pages/Clients/Clients.js
  src/pages/Clients/TabMortgage.js
  src/pages/Clients/TableClient.js
  src/pages/Clients/TabsClients.js
  src/pages/Login.js
Labels: done

#57 [IMP] filter transactions
  src/context/Transactions/TransactionsContext.js
  src/pages/Dashboard.js
  src/pages/Transactions/Transactions.js
Labels: done

#59 [IMP] filter clients by full name
  src/context/Clients/ClientsContext.js
  src/pages/Clients/Clients.js
  src/pages/Clients/TableClient.js
Labels: done

#61 [FIX] filters
  src/components/show_info/Show_info.js
  src/context/Transactions/TransactionsContext.js
  src/pages/Clients/Clients.js
Labels: done

#63 Validate interests#55 pr
  src/pages/Interests/Interests.js
  src/pages/Interests/ModalInterests.js
Labels: done

#65 Corrigiendo Cosas
  src/context/Clients/ClientsContext.js
  src/pages/Accounts/Accounts.js
  src/pages/Clients/Clients.js
  src/pages/Clients/TableClient.js
  src/pages/Clients/TabsClients.js
Labels: done

#67 Validation of Creddit Details#64
  src/pages/CreditDetails/CreditDetails.js
  src/pages/CreditDetails/ModalCreditDetails.js
Labels: done

#71 Concepts fixed
  src/pages/Concepts/Concepts.js
  src/pages/Concepts/ModalConcepts.js
Labels: done

#74 correct info to transaction table
  src/pages/Transactions/Transactions.js
Labels: assigned

#75 Fix concepts#73 pr
  src/pages/Concepts/Concepts.js
  src/pages/Concepts/ModalConceptsDescription.js
Labels: done

#79 Select
  src/pages/Clients/Clients.js
  src/pages/Clients/TabBeneficiaries.js
  src/pages/Clients/TabPersonalInfo.js
Labels: assigned

#78 Fix denominations completed #77
  src/pages/Denominations/Denominations.js
Labels: done

#82 Fix Concepts #80
  src/pages/Concepts/Concepts.js
Labels: done
